Решение задачи из раздела Основы Vue
js-tasks-ru/vue-20220419_akapin pull request #2
Opened 2022-04-27 06:49 UTC by akapin

2022-04-27 06:50 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-04-27 10:34 UTC, ShGKme requested changes
В 01-basics/03-MarkedList требуется небольшое изменение, остальные задачи приняты.

2022-04-27 10:34 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  },
Это вычисляемое свойство не помогает решить задачу, промаркировать email-ы. Оно даёт фильтрованные email-ы, но в этой задаче, в отличие от примера на вебинаре, требуется не фильтровать, а маркировать данные. 

В результате в шаблоне потребовалось заново при выводе каждого email-а проверять, а нет ли его в списке найденных, перебирая этот список (что делает метод includes). В списке, при формировании которого ранее уже проверялись все email-ы, включая текущий, то есть при вычислениях ранее уже стало известно,  что этот email нужно формировать. Такое решение получилось менее оптимальным, чем если бы email проверялся прямо в шаблоне при определении класса.

Требуется придумать, как сделать такое вычисляемое свойство, чтобы его результат сразу можно было использовать для вывода промаркированных строк, без дополнительных или повторных вычислений.

2022-04-27 10:52 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-04-27 10:54 UTC, akapin commented on 01-basics/03-MarkedList/script.js
> +  },
Отправил исправления

2022-04-28 14:08 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-04-28 14:08 UTC, merged